### PR TITLE
OracleAttestation validation and follow spec

### PR DESCRIPTION
**Pull request by bennyhodl**
Adds validation to OracleAttestation and adds `event_id` to the messaging to follow spec.

Closes https://github.com/p2pderivatives/rust-dlc/issues/239
Closes https://github.com/p2pderivatives/rust-dlc/issues/181

### CODE REVIEW

**Comment by bennyhodl** [comment]
I think the failing tests in sled are because the sled files do not have the event_id in the attestation?

**Comment by Tibo-lg** [comment]
> I think the failing tests in sled are because the sled files do not have the event_id in the attestation?

Yeah you should be able to solve this by running the `generate_serialized_contract_files.sh` script.

**Comment by bennyhodl** [comment]
I added attestation validation in line with the [spec](https://github.com/discreetlogcontracts/dlcspecs/blob/master/Oracle-Validation.md#requirements-2)

Add two test of a valid attestation and an invalid attestation where signature does not match the nonce.

**Review by Tibo-lg — APPROVED** [review]
Thanks!

**Pull request merged**
